### ISSUE TITLE
"[Ljava.lang.Object;@4bb32185" instead of question text appearing in "Question" columns of "Random 1:1s" doc

### ISSUE THREAD

**Issue by yolfer** [nextbigsoundinc/The-Way-We-Work#22]
Great script! I cloned it and I'm most of the way there. Here's what I think are repro steps:

1. Clone your google spreadsheet and update the script with the new SPREADSHEET_ID
2. Click the "Create Random 1:1 Pairings" button
3. View the "Random 1:1s" tab of the spreadsheet

Result:
![image](https://cloud.githubusercontent.com/assets/1801/10854677/73a97fa8-7efa-11e5-9bb0-d53a65a2b33f.png)

**Comment by mindweather** [comment]
Hi, Joe,
Thanks for submitting this. I know of this issue, and will try to work on it. No timeline, unfortunately. :(
If you're willing to try to debug and fix it yourself, I'd gladly take a pull request. ;)
-dz

**Comment by yolfer** [comment]
Thanks for the quick reply! I'm looking into it right now but I have about 2 minutes before my next meeting ;)
