### ISSUE TITLE
We need to further define the difference between Epic & Project.

### ISSUE THREAD

**Issue by mindweather** [nextbigsoundinc/The-Way-We-Work#25]
In general, it would be good to have the following well-defined: iteration, cycle, project, epic. Also, there is some confusion about Epic vs Project leads, especially in situations where there might be a few Projects related to the same Epic running at the same time.

**Comment by dodeca** [comment]
Here's a start. From: https://trello.com/c/eTYBF3Nl/131-what-s-the-difference-between-an-area-epic-project-and-iteration

# Area
- domains
- i.e. Front-End Engineering
	
# Epic
- multiple projects (typically 3 months+)
- i.e. Pandora Data Integration & Access

# Project 
- multiple iterations (typically 1 month+)
- i.e. Integrate Pandora Data
	
# Iteration
- two week dedicated sprint
- i.e. ingest test files for Pandora Spin data
